spring:
  application:
    name: configserver
  cloud:
    config:
      server:
        git:
          uri: https://github.com/srnecmatija/spring-boot-cloud-demo
          search-paths: configuration
server:
  port: 8888
